### ISSUE TITLE
More detailed example

### ISSUE THREAD

**Issue by chriscalo** [geddski/grunt-clear#1]
Can you provide a more detailed example? I copy the following into my `grunt.js` file:

```
watch: {
  clear: {
    //clear terminal on any watch task. beauty.
    files: ['**/*'], //or be more specific
    tasks: ['clear']
  }
}
```

And I get the following error:

```
TaskError: Task "clear" not found.
```

**Comment by geddski** [comment]
Hey @chriscalo. You're probably missing this in your Gruntfile:
`grunt.loadNpmTasks('grunt-clear');`

See the full readme for instructions. Let me know if you're still having trouble.

**Comment by chriscalo** [comment]
Turns out my problem was that `grunt.loadNpmTasks` doesn't search for globally installed modules. Shame. Thanks for the quick reply.

**Comment by geddski** [comment]
awesome
